# Generated by Django 3.0.7 on 2020-06-23 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0004_auto_20200621_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='builds',
            name='engine_parts',
            field=models.ManyToManyField(blank=True, null=True, to='builds.Engine'),
        ),
        migrations.AlterField(
            model_name='builds',
            name='exterior_parts',
            field=models.ManyToManyField(blank=True, null=True, to='builds.Exterior'),
        ),
        migrations.AlterField(
            model_name='builds',
            name='interior_parts',
            field=models.ManyToManyField(blank=True, null=True, to='builds.Interior'),
        ),
        migrations.AlterField(
            model_name='builds',
            name='running_gear_parts',
            field=models.ManyToManyField(blank=True, null=True, to='builds.Running'),
        ),
    ]
