# Generated by Django 3.0.7 on 2020-06-23 20:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('builds', '0005_auto_20200623_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='builds',
            name='dislikes',
            field=models.ManyToManyField(blank=True, null=True, related_name='builds_dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='builds',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='builds_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
