# Generated by Django 3.0.7 on 2020-06-23 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0006_auto_20200623_2112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='builds',
            options={'ordering': ('-id',)},
        ),
    ]
