# Generated by Django 3.0.7 on 2020-07-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0008_auto_20200703_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engine',
            name='link',
            field=models.URLField(max_length=400),
        ),
        migrations.AlterField(
            model_name='exterior',
            name='link',
            field=models.URLField(max_length=400),
        ),
        migrations.AlterField(
            model_name='interior',
            name='link',
            field=models.URLField(max_length=400),
        ),
        migrations.AlterField(
            model_name='running',
            name='link',
            field=models.URLField(max_length=400),
        ),
    ]
