# Generated by Django 3.0.7 on 2020-07-21 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0009_auto_20200712_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='builds',
            name='build_id',
            field=models.CharField(blank=True, editable=False, max_length=32, null=True, unique=True),
        ),
    ]
