# Generated by Django 3.0.7 on 2020-07-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0010_builds_build_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='builds',
            name='price_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
