# Generated by Django 3.0.7 on 2020-08-01 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0013_auto_20200729_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engine',
            name='link',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='exterior',
            name='link',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='interior',
            name='link',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='running',
            name='link',
            field=models.URLField(max_length=500),
        ),
    ]
