# Generated by Django 3.0.7 on 2020-08-08 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0014_auto_20200801_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='builds',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes'),
        ),
    ]
