version: '3.10'
services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: autoskunkworks
    restart: unless-stopped
    env_file:
      - '.env'
    volumes:
      - static_volume:/backend/static
    command: >
            sh -c "python manage.py collectstatic --noinput &&
            python manage.py migrate &&
            gunicorn autoskunkworks.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    restart: always
    image: postgres:13
    container_name: autoskunkworks-postgres 
    env_file:
      - '.env'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/

  nginx:
    image: nginx:latest
    container_name: asw-nginx
    restart: always
    ports:
        - "82:8080"
    volumes:
        - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
        - static_volume:/var/www/backend/static
    depends_on:
        - web

volumes:
  static_volume: