# Generated by Django 3.0.7 on 2020-08-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='admin_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='category',
            field=models.CharField(choices=[('1', 'Bug'), ('2', 'Duplicate'), ('3', 'Enhancement'), ('4', 'Wont Fix'), ('5', 'Question'), ('6', 'Other')], default='1', max_length=11),
        ),
    ]
